-- INSERT INTO public.empleados(nombre, apellido,depto, salario) VALUES('Juan','Lopez Lopez',1,23000.0);
-- INSERT INTO public.empleados(nombre, apellido,depto, salario) VALUES('Mariana','Alcantara Villegas',2,25000.0);
-- INSERT INTO public.empleados(nombre, apellido,depto, salario) VALUES('Ana Lilia','Torres Velardes',3,20000.0);
-- INSERT INTO public.empleados(nombre, apellido,depto, salario) VALUES('Hugo','Alvirdes Corona',3,24000.0);
-- INSERT INTO public.empleados(nombre, apellido,depto, salario) VALUES('Karla','Cortes Velez',1,16000.0);
-- INSERT INTO public.empleados(nombre, apellido,depto, salario) VALUES('Yuridiana','Lopez Valdez',1,23000.0);
-- INSERT INTO public.empleados(nombre, apellido,depto, salario) VALUES('Jacinto','Gutierrez Delarde',3,24000.0);
-- INSERT INTO public.empleados(nombre, apellido,depto, salario) VALUES('Adriana','Matamoros Mori',4,23000.0);
